### ISSUE TITLE
Error: Error parsing connection string: invalid port number

### ISSUE THREAD

**Issue by omar-dulaimi** [prisma/p1-to-p2-upgrade-path-feedback#12]
## Which docs page are you referring to?
https://www.prisma.io/docs/guides/upgrade-guides/upgrade-from-prisma-1/upgrading-the-prisma-layer-postgres

## What issue or question did you encounter with that page?

When constructing the connection string for mysql, I receive an error in the terminal:

Error: Error parsing connection string: invalid port number in 
`mysql://username:password@server:port/username?schema=default@default`)

## Do you have suggestions how we could improve or exend the content?

I'm not sure what exactly causing this issue, but I think it's related to escaping certain characters. So the suggestion is that the doc page should mention what characters are allowed and how to escape certain others.

**Comment by Jolg42** [comment]
So the problem is that the uri special characters in your password needs to be encoded see https://github.com/prisma/docs/issues/1057
